name: asyugon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
 
  flutter:
    sdk: flutter
  arcore_flutter_plugin:
  # fancy_bar: ^1.2.0
  # flutter_rating_bar: ^3.0.1+1
  fluttertoast: ^7.0.1+1
  # google_sign_in: 
  # flutter_facebook_login:
  # agora_rtc_engine: ^1.0.15
  # permission_handler: ^4.4.0+hotfix.2
  # web_socket_channel: ^1.1.0
  # firebase_database: ^3.1.3
  # firebase_storage:
  # time_formatter: ^1.0.0
  intl:
  # geolocator: ^5.1.3
  # geoflutterfire: any
  # introduction_screen: ^1.0.7
  # geocoder: ^0.2.1
  # location: ^2.3.5
  # pdf:
  # printing: ^3.3.1
  # http:
  # provider: ^3.1.0
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  shared_preferences: ^0.5.7+3
  firebase_messaging:
  cached_network_image: 
  flutter_local_notifications: ^1.4.4+4
  photo_view: ^0.10.2
  # floating_bottom_navigation_bar: ^1.0.2
  # image_picker: 
  # typicons_flutter:
  # google_maps_flutter:
  # flutter_dash:
  # razorpay_flutter: ^1.1.4
  # firebase_dynamic_links: ^0.5.1
  # dotted_border: ^1.0.5
  # url_launcher: ^5.5.2
  # youtube_player_flutter:
  # font_awesome_flutter:
  # agora_rtm:
  # wakelock: ^0.1.4+1
  # flutter_spinkit: ^4.1.2
  # flutter_custom_clippers: ^1.1.1
  # flutter_svg: ^0.18.0
  # speech_to_text: ^2.2.0
  # flutter_dialogflow_v2: ^0.3.1
  # flutter_auth_buttons: ^0.8.0
  # hive: ^1.4.2
  # hive_flutter: ^0.3.1
  # path_provider:
  # path:
  image_picker: ^0.6.7+8
  google_sign_in: ^4.5.3
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_database: ^4.0.0
  firebase_storage: ^4.0.0
  # datetime_picker_formfield: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter	
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
